package MYSQL;

public class Join {
//    SELECT p.PRODUCT_CODE AS 'PRODUCT_ID',
//    SUM(p.PRICE * o.SALES_AMOUNT) AS 'SALES'
//    FROM PRODUCT p
//    JOIN OFFLINE_SALE o
//    ON p.PRODUCT_ID = o.PRODUCT_ID
//    GROUP BY o.PRODUCT_ID
//    ORDER BY SALES DESC, PRODUCT_CODE ASC
//
//    SELECT b.BOOK_ID AS BOOK_ID,
//    a.AUTHOR_NAME AS AUTHOR_NAME,
//    DATE_FORMAT(b.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
//    FROM BOOK b
//    LEFT JOIN AUTHOR a
//    ON b.AUTHOR_ID = a.AUTHOR_ID
//    WHERE b.CATEGORY = '경제'
//    ORDER BY 3
//
//    SELECT o.ANIMAL_ID, o.NAME
//    FROM ANIMAL_OUTS o
//    LEFT OUTER JOIN ANIMAL_INS i
//    ON i.ANIMAL_ID = o.ANIMAL_ID
//    WHERE i.ANIMAL_ID IS NULL
//    ORDER BY 1
//
//    SELECT i.ANIMAL_ID, i.NAME
//    FROM ANIMAL_INS i
//    LEFT JOIN ANIMAL_OUTS o
//    ON i.ANIMAL_ID = o.ANIMAL_ID
//    WHERE i.DATETIME > o.DATETIME
//    ORDER BY i.DATETIME
//
//    SELECT NAME, DATETIME
//    FROM ANIMAL_INS
//    WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID
//                       FROM ANIMAL_OUTS)
//    ORDER BY DATETIME
//    LIMIT 3
//
//    SELECT c.CAR_ID,
//    c.CAR_TYPE,
//    ROUND(c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE)/100) AS FEE
//    FROM CAR_RENTAL_COMPANY_CAR c
//    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
//    ON c.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE = '30일 이상'
//    WHERE 1=1
//    AND c.CAR_TYPE IN ('세단','SUV')
//    AND c.CAR_ID NOT IN (SELECT CAR_ID
//                             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
//                                     WHERE START_DATE <= '2022-11-30'
//                                     AND END_DATE >= '2022-11-01')
//    HAVING FEE >= 500000 AND FEE < 2000000
//    ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC
//
//    SELECT p.PRODUCT_ID,
//    p.PRODUCT_NAME,
//    sum(o.AMOUNT * p.PRICE) AS TOTAL_SALES
//    FROM FOOD_PRODUCT p
//    JOIN FOOD_ORDER o
//    ON p.PRODUCT_ID = o.PRODUCT_ID
//    WHERE o.PRODUCE_DATE like '2022-05%'
//    GROUP BY PRODUCT_ID
//    ORDER BY 3 DESC, 1 ASC
}
