package MYSQL;

public class Programmers284529 {
//    1.
//    SELECT d.DEPT_ID, d.DEPT_NAME_EN, ROUND(AVG(e.SAL)) AS 'AVG_SAL'
//    FROM HR_DEPARTMENT d JOIN HR_EMPLOYEES e ON d.DEPT_ID = e.DEPT_ID
//    GROUP BY DEPT_ID
//    ORDER BY 3 DESC
//
//    2.
//    SELECT d.DEPT_ID, d.DEPT_NAME_EN, ROUND(AVG(e.SAL)) AS 'AVG_SAL'
//    FROM HR_DEPARTMENT d, HR_EMPLOYEES e
//    WHERE d.DEPT_ID = e.DEPT_ID
//    GROUP BY DEPT_ID
//    ORDER BY 3 DESC
}
