package MYSQL;

public class Select {
//    SELECT ROUND(AVG(DAILY_FEE),0) AS AVERAGE_FEE
//    FROM CAR_RENTAL_COMPANY_CAR
//    WHERE CAR_TYPE like 'SUV'
//
//    SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD,'%Y-%m-%d') AS HIRE_YMD
//    FROM DOCTOR
//    WHERE MCDP_CD IN ('CS','GS')
//    ORDER BY 4 DESC, 1 ASC
//
//    SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
//    FROM FOOD_FACTORY
//    WHERE ADDRESS like '강원도%'
//    ORDER BY 1
//
//    SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO,'NONE') AS TLNO
//    FROM PATIENT
//    WHERE 1=1
//    AND AGE <= 12
//    AND GEND_CD like 'W'
//    ORDER BY 4 DESC, 1 ASC
}
